defaults: # for loading the default.yaml config
  - task: panoptic

  - visualization: default
  - lr_scheduler: exponential
  - training: default
#
  - debugging: default
  - models: ??? #"outputs/2022-03-16/14-25-38"
  - data: ??? #panoptic/sbub

job_name: benchmark # prefix name for saving the experiment file.
model_name: PointGroup-PAPER # Name of the specific model to load
update_lr_scheduler_on: "on_epoch" # ["on_epoch", "on_num_batch", "on_num_sample"]
selection_stage: ""
pretty_print: True
eval_frequency: 1

tracker_options: # Extra options for the tracker
  full_res: False
  make_submission: False
  track_boxes: False